name: mint_flutter_extensions
description: >
  Speed up your Flutter development process by
  reducing boilerplate code with easy-to-use extensions.
version: 0.2.0
homepage: https://github.com/m11v
repository: https://github.com/m11v/mint_flutter_extensions

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
